load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_vite//:defs.bzl", "vite_build", "vite_run", "vitest_test")

npm_link_all_packages(name = "node_modules")

SRCS = glob(["src/**"]) + [
    "index.html",
    "package.json",
    "vite.config.ts",
]

APP_DEPS = [
    ":node_modules/@vitejs/plugin-react",
    ":node_modules/react",
    ":node_modules/react-dom",
    ":node_modules/vite",
]

vite_build(
    name = "web_vite_derived",
    srcs = SRCS,
    node_modules = ":node_modules",
)

vite_build(
    name = "web_deps_vite_derived",
    srcs = SRCS,
    deps = APP_DEPS,
)

vitest_test(
    name = "unit_tests_vitest_derived",
    srcs = SRCS,
    config = "vite.config.ts",
    node_modules = ":node_modules",
)

vitest_test(
    name = "unit_tests_deps_vitest_derived",
    srcs = SRCS,
    config = "vite.config.ts",
    deps = APP_DEPS + [":node_modules/vitest"],
)

vite_run(
    name = "web_vite_derived.dev",
    node_modules = ":node_modules",
)
