module(
    name = "rules_vite",
    version = "0.1.0",
    bazel_compatibility = [">=8.0.0"],
    compatibility_level = 1,
)

bazel_dep(name = "aspect_rules_js", version = "3.1.2")
bazel_dep(name = "hermetic_launcher", version = "0.0.14")
bazel_dep(name = "rules_nodejs", version = "6.7.4")
bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")

bazel_dep(name = "buildifier_prebuilt", version = "10.1.0", dev_dependency = True)
bazel_dep(name = "bazel_skylib", version = "1.9.0", dev_dependency = True)
bazel_dep(name = "aspect_gazelle_prebuilt", version = "0.0.18", dev_dependency = True)
bazel_dep(name = "stardoc", version = "0.8.1", dev_dependency = True)

shadcn = use_extension("@rules_vite//shadcn:extensions.bzl", "shadcn", dev_dependency = True)
shadcn.components(
    name = "shadcn",
    lock = "//private/snapshots:lock.json",
)
use_repo(shadcn, "shadcn")
