"""Repository rules for shadcn component downloads.

chadcn_components_repo downloads registry JSON pinned by sha256, extracts
the component source files from files[].content, and exposes each as a
js_library. chadcn_cli_repo fetches the shadcn CLI npm tarball.
"""

def _extract_component(rctx, name, entry, seen):
    """Downloads a component JSON and extracts its files. Returns (files, transitive_dep_names)."""
    if name in seen:
        return [], []
    seen[name] = True

    raw = rctx.download(
        url = entry["url"],
        sha256 = entry["sha256"],
        output = "_raw/%s.json" % name,
    )
    if not raw.success:
        fail("chadcn: failed to download %s from %s" % (name, entry["url"]))

    spec = json.decode(rctx.read("_raw/%s.json" % name))

    files = []
    for f in spec.get("files", []):
        content = f.get("content", "")
        if not content:
            continue
        target = f["path"]
        if "/" in target:
            target = target.split("/")[-1]
        rctx.file(
            "components/%s/%s" % (name, target),
            content,
            executable = False,
        )
        files.append(target)

    return files, spec.get("registryDependencies", [])

def _chadcn_components_repo_impl(rctx):
    lock = json.decode(rctx.read(rctx.attr.lock))
    components = lock.get("components", {})

    build_parts = [
        "# @generated by rules_vite chadcn_components_repo - do not edit",
        "load(\"@rules_vite//private/helpers:js_library.bzl\", \"js_library\")",
        "exports_files(glob([\"components/**\"]))",
    ]

    seen = {}
    for name in sorted(components.keys()):
        entry = components[name]
        if not entry.get("url") or not entry.get("sha256"):
            fail("chadcn lock entry %s needs both url and sha256" % name)

        _files, registry_deps = _extract_component(rctx, name, entry, seen)

        for dep_name in registry_deps:
            dep_entry = components.get(dep_name)
            if dep_entry:
                _extract_component(rctx, dep_name, dep_entry, seen)
            else:
                build_parts.append("# registry dependency %s not in lock; add it to consume" % dep_name)

        build_parts.append(
            "js_library(name = \"%s\", srcs = glob([\"components/%s/**\"]), visibility = [\"//visibility:public\"])" %
            (name.replace("/", "_"), name),
        )

    rctx.file("BUILD.bazel", "\n".join(build_parts) + "\n")
    rctx.delete("_raw")

chadcn_components_repo = repository_rule(
    implementation = _chadcn_components_repo_impl,
    attrs = {
        "lock": attr.label(
            mandatory = True,
            allow_single_file = True,
        ),
    },
)

def _chadcn_cli_repo_impl(rctx):
    if not rctx.attr.sha256:
        fail("chadcn cli requires the npm tarball sha256; pin it in the tag")
    rctx.download_and_extract(
        url = "https://registry.npmjs.org/shadcn/-/shadcn-%s.tgz" % rctx.attr.version,
        sha256 = rctx.attr.sha256,
    )
    rctx.file(
        "BUILD.bazel",
        "# @generated by rules_vite chadcn_cli_repo - do not edit\n" +
        "exports_files([\"package/bin/cli.js\"])\n" +
        "filegroup(name = \"cli_files\", srcs = glob([\"package/**\"]), visibility = [\"//visibility:public\"])\n",
    )

chadcn_cli_repo = repository_rule(
    implementation = _chadcn_cli_repo_impl,
    attrs = {
        "version": attr.string(mandatory = True),
        "sha256": attr.string(mandatory = True),
    },
)
