"""Helpers shared by the rules."""

load("@aspect_bazel_lib//:bzl_library.bzl", "bzl_library")

exports_files([
    "js_library.bzl",
    "js_stub_binary.bzl",
    "node.bzl",
])

bzl_library(
    name = "js_library",
    srcs = ["js_library.bzl"],
    visibility = ["//visibility:public"],
    deps = ["@aspect_rules_js//js:defs"],
)

bzl_library(
    name = "js_stub_binary",
    srcs = ["js_stub_binary.bzl"],
    visibility = ["//visibility:public"],
    deps = ["@hermetic_launcher//launcher:lib_bzl"],
)

bzl_library(
    name = "node",
    srcs = ["node.bzl"],
    visibility = ["//visibility:public"],
)
